#pragma once

constexpr const char* ps_sdf = ""
"ps.1.4"																				"\r\n"
""																						"\r\n"
// c0(scale/thickness) 由运行时设置
"									// c0.y: The thickness value of the text"			"\r\n"
"def		c1, 0.0625, 0, 0, 0		// c1.x: the compensation of mad_x8 (0.5 / 8)"		"\r\n"
""																						"\r\n"
"texld		r0, t0"																		"\r\n"
""																						"\r\n"
"sub		r1.a, r0.a, c0.y"															"\r\n"
"mov_x2		r2.x, c0.x"																	"\r\n"
"mad_x8_sat r1.a, r1_x2.a, r2.x, c1.x"													"\r\n"
""																						"\r\n"
"mov		r0.rgb, v0"																	"\r\n"
"+mul		r0.a, r1.a, v0.a	// final_alpha = sdf_alpha * alpha"						"\r\n";

constexpr const char* ps_sdf_premul = ""
"ps.1.4"																				"\r\n"
""																						"\r\n"
// c0(scale/thickness) 由运行时设置
"									// c0.y: The thickness value of the text"			"\r\n"
"def		c1, 0.0625, 0, 0, 0		// c1.x: the compensation of mad_x8 (0.5 / 8)"		"\r\n"
""																						"\r\n"
"texld		r0, t0"																		"\r\n"
""																						"\r\n"
"sub		r1.a, r0.a, c0.y"															"\r\n"
"mov_x2		r2.x, c0.x"																	"\r\n"
"mad_x8_sat r1.a, r1_x2.a, r2.x, c1.x"													"\r\n"
""																						"\r\n"
"mov		r0.rgb, v0"																	"\r\n"
"+mul		r0.a, r1.a, v0.a	// final_alpha = sdf_alpha * alpha"						"\r\n"
""																						"\r\n"
"mul		r0.rgb,  r0, r0.a	// Pre-multiplied alpha"								"\r\n";

constexpr const char* ps_sdf_hlsl = ""
"sampler2D u_texture;"															"\r\n"
"float u_buffer;    // SDF 阈值(thickness): 0.1~0.9, 默认 0.5"					"\r\n"
"float u_gamma;     // 边缘软度(与 sharpness 成反比), 默认约 0.03"					"\r\n"
""																				"\r\n"
"float4 mainPS(float2 v_texcoord : TEXCOORD0,"									"\r\n"
"              float4 v_color    : COLOR0) : COLOR0"							"\r\n"
"{"																				"\r\n"
"    float dist = tex2D(u_texture, v_texcoord).a;  // A8 图集 → alpha"			"\r\n"
"    float alpha = smoothstep(u_buffer - u_gamma, u_buffer + u_gamma, dist);"	"\r\n"
"    return float4(v_color.rgb, alpha * v_color.a);"							"\r\n"
"}"																				"\r\n";

constexpr const char* ps_sdf_hlsl_premul = ""
"sampler2D u_texture;"															"\r\n"
"float u_buffer;"																"\r\n"
"float u_gamma;"																"\r\n"
""																				"\r\n"
"float4 mainPS(float2 v_texcoord : TEXCOORD0,"									"\r\n"
"              float4 v_color    : COLOR0) : COLOR0"							"\r\n"
"{"																				"\r\n"
"    float dist = tex2D(u_texture, v_texcoord).a;"								"\r\n"
"    float alpha = smoothstep(u_buffer - u_gamma, u_buffer + u_gamma, dist);"	"\r\n"
"    float a = alpha * v_color.a;"												"\r\n"
"    return float4(v_color.rgb * a, a);"										"\r\n"
"}"																				"\r\n";