#pragma once

constexpr const char* ps_sdf = ""
"ps.1.4"																				"\r\n"
""																						"\r\n"
"def		c0, 0.75, 0.5, 0, 0		// c0.x: The 1/32 of the scale"						"\r\n"
"									// c0.y: The thickness value of the text"			"\r\n"
"def		c1, 0.0625, 0, 0, 0		// c1.x: the compensation of mad_x8 (0.5 / 8)"		"\r\n"
""																						"\r\n"
"texld		r0, t0"																		"\r\n"
""																						"\r\n"
"sub		r1.a, r0.a, c0.y"															"\r\n"
"mov_x2		r2.x, c0.x"																	"\r\n"
"mad_x8_sat r1.a, r1_x2.a, r2.x, c1.x"													"\r\n"
""																						"\r\n"
"mov		r0.rgb, v0"																	"\r\n"
"+mul		r0.a, r1.a, v0.a	// final_alpha = sdf_alpha * alpha"						"\r\n"
""																						"\r\n"
"mul		r0,      r0, v0		// Blend"												"\r\n";

constexpr const char* ps_sdf_premul = ""
"ps.1.4"																				"\r\n"
""																						"\r\n"
"def		c0, 0.75, 0.5, 0, 0		// c0.x: The 1/32 of the scale"						"\r\n"
"									// c0.y: The thickness value of the text"			"\r\n"
"def		c1, 0.0625, 0, 0, 0		// c1.x: the compensation of mad_x8 (0.5 / 8)"		"\r\n"
""																						"\r\n"
"texld		r0, t0"																		"\r\n"
""																						"\r\n"
"sub		r1.a, r0.a, c0.y"															"\r\n"
"mov_x2		r2.x, c0.x"																	"\r\n"
"mad_x8_sat r1.a, r1_x2.a, r2.x, c1.x"													"\r\n"
""																						"\r\n"
"mov		r0.rgb, v0"																	"\r\n"
"+mul		r0.a, r1.a, v0.a	// final_alpha = sdf_alpha * alpha"						"\r\n"
""																						"\r\n"
"mul		r0,      r0, v0		// Blend"												"\r\n"
"mul		r0.rgb,  r0, r0.a	// Pre-multiplied alpha"								"\r\n";